### ISSUE TITLE
Do not create (Klarna) orders when directing to the payment site

### ISSUE THREAD

**Issue by SandyMental** [mollie/Shopware#10]
Hi there,

the behaviour of mollie to create "real" orders before the final checkout-step is very unusual for Shopware and brings for me at least one problem when this is given:
- having one article in the basket, that has a stock of only 1
- choose a klarna payment option
- get directed to the payment site of mollie
- cancel this order

So now  you get redirected back to the shop  with an EMPTY cart giving the customer the option to restore their "cancelled order" (in fact the payment was cancelled, not the order!)
What happens when clicking restore? The costumer ends up with an empty basket and if it was a guest user, he is logged out too and that means: All the way from the beginning to get to the checkout. 
This is quite frustrating as a costumer.

Is there any practical and technical reason why you create orders before the final checkout-page? Please consider to change this behaviour, that is not common for shopware payment plugins. Expected would be, to get redirected to the checkout to choose another payment option.
Not to create an anyways cancelled order, whose stocks cant be retrieved correctly when trying to restore the order.

thx!

**Comment by KienerNL** [comment]
Hi there,

There was a technical reason: the Orders API (that was first integrated in version 1.3, necessary for Klarna Pay Later) required the order number. This is still the case, though the difference is that it can be changed afterwards. So now we can start the payment with a temporary number and later add the number of the created order to the order at Mollie.

I can brighten up your day a little. We're working on making it configurable now. Some merchants like the order to be created beforehand because than Mollie shows the correct order number in the payment screen. Other merchants don't like it, or experience some difficulties with. Therefore we'd like to support both options.

The new plugin is in the works and is expected to be released next week.

My kind regards,
Reinder.

**Comment by SandyMental** [comment]
is this fixed in 1.4.5?
