### ISSUE TITLE
Cancellation of total amount and shipping not functioning correctly

### ISSUE THREAD

**Issue by padrini** [mollie/Shopware#226]
In the 1.8.4 update we have a setting called _Cancellation of total amount and shipping_ this one is set on No as default.
But when a order is cancelled the Order total amount becomes less than it should be, only the shipping is then used as the total amount of the order.

Below some screenshots of the situation inside a order we see happening after updating to 1.8.4

![image](https://user-images.githubusercontent.com/7999184/122362662-9ba0a400-cf58-11eb-88d3-b86a2d9ffe66.png)
![image](https://user-images.githubusercontent.com/7999184/122362763-b246fb00-cf58-11eb-9206-ce5e0db5e5e0.png)
![image](https://user-images.githubusercontent.com/7999184/122362842-c1c64400-cf58-11eb-9918-0de2c27e18e9.png)
![image](https://user-images.githubusercontent.com/7999184/122362877-c854bb80-cf58-11eb-9b8d-48e552b1f872.png)

**Comment by boxblinkracer** [comment]
hi

thank you for your message

if only the shipping is left, but the rest is cancelled, then it might be due to "reset stock on failed payments"
this one resets the order positions to a quantity of 0 which automatically affects the total price

could that be?

the settings are indeed a bit confusing sometimes, but unfortunately necessary to support things like pickware,
but maybe i can at least improve the wording

**Comment by padrini** [comment]
Hi Cristian, 

Thank you for your reply. 
That will probably be it then, because we got that one set to Yes in the configuration.

Maybe a improving of the wording would already help a lot in understanding what is happening there for other users of the plugin.

**Comment by padrini** [comment]
Yes than this issue can be closed.
