### ISSUE TITLE
"Warning, Mollie is paid but no order exists in Shopware for transaction xxxx"

### ISSUE THREAD

**Issue by SandyMental** [mollie/Shopware#254]
Since the recent update, this happens with every order. 
We have transactions in mollie, but no order data in SW.
For non-Klarna orders this is super frustrating as we have no customer data now!

I can provide more logs and settings of the plugin later.

This is the error:
Checkout failed when finishing Order for Transaction: 664 (Session: i92n...)

{
  "error": "Order with number:  not found!",
  "session": "i92n3s27vb9novut6u9bau052q",
  "processors": {
    "uid": {
      "uid": "8cc7101"
    },
    "web": {
      "url": "/Mollie/finish/transactionNumber/664",
      "ip": "127.0.0.*",
      "http_method": "GET",
      "server": "psy7.com",
      "referrer": "https://pay.klarna.com/"
    },
    "introspection": {
      "file": null,
      "line": null,
      "class": "Shopware_Controllers_Frontend_Mollie",
      "function": "finishAction"
    }
  }
}

**Comment by boxblinkracer** [comment]
Hi

thank you for this

do you see any error logs somehwere? i think in the core logs there might be something like "paymentID null".
and also in the mollie logs something like "session restoring"?

then you probably have create orders AFTER payment?
this one in combination with session data that is gone, might lead to this.

in the mollie plugin, theres only shopware standard used to restore the session.
we try to avoid duplicating shopware code in order to allow smooth shopware updates.
the sSaveOrder of shopware requires session data though. if they are gone, then the order cannot be saved from shopware.

i will also write an article in the wiki about this soon

let me know if this might be the case with that transaction

**Comment by SandyMental** [comment]
yes we create orders AFTER payment, as the other way around we only had problems in combination with Pickware, article stocks and failed orders filling the database. 
I can understand that it "might" lead to this situation, yet till the update this was super rare.
Now it happens in a row with every order coming through mollie.

When one can confirm that these issues are all from the past and they are fixed accordingly I could try the setting to create orders before payment is finished. 

So after a quick view at the logs I cannot find anything mentioned. Will have a closer look in the evening

**Comment by boxblinkracer** [comment]
Hi
i just had that problem in another shop, and it was working after deactivating and activating the plugin.
i think it might have been due to a cache problem

could you try this for me?

**Comment by SandyMental** [comment]
Hi there,

that seems to work.

thank you

**Comment by boxblinkracer** [comment]
Hi

that is weird, so a cache thing i guess
thank you so much for your response

i would now close this issue and use it as a reference in case it happens again
thank you
