### ISSUE TITLE
Show Apple Pay in Shopware 5 Checkout

### ISSUE THREAD

**Issue by bwdcd** [mollie/Shopware#319]
Hello,

we had Mollie live in our online store since yesterday.

The activated payment method "Apple Pay"  is not displayed in the checkout on desktop applications "Safari" and "Google Chrome". All settings are set correctly and "Apple Pay" is not excluded on any page.

Our online store is www.bestwaystore.de

Do you have the possibility to identify the cause?

Thank you for your support.

With kind regards
Christian

**Comment by boxblinkracer** [comment]
Hi
thank you for your message

so Apple Pay isn't available in chrome for example...only on specific browsers and if you also have a valid Apple Pay credit card in your Apple Account.
we have a documentation where you can also find a playground website from apple where you can test if the apple pay button would even appear in your browser
https://github.com/mollie/Shopware/wiki/Apple-Pay

besides that, its "just" a simple payment method. so make sure to activate it and have it being displayed (no risk management things....).
then it should be in the list of the payment methods in the checkout.
if its still not there, it might be very likely hidden due to the browser not being valid for the payment method (see wiki link above)

i hope this helps you

**Comment by boxblinkracer** [comment]
Hi

i would now close this ticket due to inactivity :)
just let me know if you need more help, thank you
