### ISSUE TITLE
Order being made twice

### ISSUE THREAD

**Issue by powolnymarcel** [mollie/Shopware#62]
Hello,

I have noticed a strange behavior with the orders. I don't know if it's related to Shopware, Mollie or the customer himself.

Sometime orders are being added twice (two first rows and 2 last rows)
https://i.ibb.co/bmRdRXG/Capture.png

What do you think ?

**Comment by boxblinkracer** [comment]
Hi

this is shopware 6 right?
so it would belong here: https://github.com/mollie/Shopware6
i'm just saying that, because WE only maintain shopware 5 ;)

still interesting thing, we also do lots of shopware 6 shops and i think i just heard about that problem yesterday.
it was also with another PSP...so not mollie.
i think the reason was a double click of the user when doing the checkout. maybe its related to this here

cheers
christian

**Comment by boxblinkracer** [comment]
Hi

alright so i've asked for more details in my company
the button events got triggered twice on double clicks
so what they basically did was to preventDefault after the first click, so its not fired twice

with that in mind, you could try to reproduce it and fix it.
please pay attention to additional events that might be chained and added to the onClick...just to say that :D

cheers
christian

**Comment by powolnymarcel** [comment]
Thanks a lot ! and thank you to your colleagues at dasistweb 😊

**Comment by boxblinkracer** [comment]
no problem
thank you, i'll let them know :)
